/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FromRouteImport } from './routes/from'
import { Route as IndexRouteImport } from './routes/index'

const FromRoute = FromRouteImport.update({
  id: '/from',
  path: '/from',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/from': typeof FromRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/from': typeof FromRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/from': typeof FromRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/from'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/from'
  id: '__root__' | '/' | '/from'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FromRoute: typeof FromRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/from': {
      id: '/from'
      path: '/from'
      fullPath: '/from'
      preLoaderRoute: typeof FromRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FromRoute: FromRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
