/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FromRouteImport } from './routes/from'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransferSuccessRouteImport } from './routes/transfer/success'
import { Route as ToSuccessRouteImport } from './routes/to/success'

const FromRoute = FromRouteImport.update({
  id: '/from',
  path: '/from',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferSuccessRoute = TransferSuccessRouteImport.update({
  id: '/transfer/success',
  path: '/transfer/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ToSuccessRoute = ToSuccessRouteImport.update({
  id: '/to/success',
  path: '/to/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/from': typeof FromRoute
  '/to/success': typeof ToSuccessRoute
  '/transfer/success': typeof TransferSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/from': typeof FromRoute
  '/to/success': typeof ToSuccessRoute
  '/transfer/success': typeof TransferSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/from': typeof FromRoute
  '/to/success': typeof ToSuccessRoute
  '/transfer/success': typeof TransferSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/from' | '/to/success' | '/transfer/success'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/from' | '/to/success' | '/transfer/success'
  id: '__root__' | '/' | '/from' | '/to/success' | '/transfer/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FromRoute: typeof FromRoute
  ToSuccessRoute: typeof ToSuccessRoute
  TransferSuccessRoute: typeof TransferSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/from': {
      id: '/from'
      path: '/from'
      fullPath: '/from'
      preLoaderRoute: typeof FromRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer/success': {
      id: '/transfer/success'
      path: '/transfer/success'
      fullPath: '/transfer/success'
      preLoaderRoute: typeof TransferSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/to/success': {
      id: '/to/success'
      path: '/to/success'
      fullPath: '/to/success'
      preLoaderRoute: typeof ToSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FromRoute: FromRoute,
  ToSuccessRoute: ToSuccessRoute,
  TransferSuccessRoute: TransferSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
